language: php

php:
  - 7.1
  - 7.2

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version
  - composer install

script:
  # Run full test suite and linting of the code base
  - composer php:codesniffer